# Site settings
title:          blog
description:    "notes about code, setups, workflow and why your favorite editor is the best one ever"
baseurl:        "/blog"
url:            ""
author:         rahul
portfolio_url:    "https://crypticsaiyan.me"
portfolio_label:  "crypticsaiyan"
github_url:       "https://github.com/crypticsaiyan/blog"

# https://jekyllrb.com/docs/configuration/options/
timezone: Asia/Kolkata

style_light: mocha
style_dark: mocha

#include pages
include:
  - _pages

# Assets
sass:
  sass_dir:     /assets/css/_sass
  style:        compressed

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
